name: VClans
version: '0.7'
main: gg.valentinos.alexjoo.VClans
api-version: '1.21'
authors: [ Alex_Joo ]
description: VClans, short for Valentinos Clans, is a faction-like plugin where you can create your own faction, claim your own land, declare war with other or choose to be a pacifist.
website: valentinos.gg
softdepend:
  - BlueMap
  - Vault
  - WorldGuard
commands:
  clan:
    description: Handles all clan related commands.
    usage: /clan help
    aliases: [ c ]
  war:
    description: Handles all clan war related commands.
    usage: /war help
    aliases: [ w ]
  chunk:
    description: Handles all chunk related commands.
    usage: /chunk help
    aliases: [ ch ]
  confirm:
    description: Confirm your action.
    usage: /confirm
  cancel:
    description: Cancels your action.
    usage: /cancel
  test:
    description: This is VClans test command. you should not see this
    usage: /test

