name: VClans
version: '0.4'
main: gg.valentinos.alexjoo.VClans
api-version: '1.21'
authors: [ Alex_Joo ]
description: VClans, short for Valentinos Clans, is a faction-like plugin where you can create your own faction, claim your own land, declare war with other or choose to be a pacifist.
website: valentinos.gg
softdepend:
  - bluemap
  - vault
commands:
  clan:
    description: Handles all clan related commands.
    usage: /clan help
    aliases: [ c ]
  chunk:
    description: Handles all chunk related commands.
    usage: /chunk help
    aliases: [ ch ]
  confirm:
    description: Confirm your action.
    usage: /confirm

