name: VClans
version: '0.12'
main: gg.valentinos.alexjoo.VClans
api-version: '1.21.8'
authors: [ Alex_Joo ]
description: VClans, short for Valentinos Clans, is a faction-like plugin where you can create your own faction, claim your own land, declare war with other or choose to be a pacifist.
website: valentinos.gg
softdepend:
  - Vault
  - Essentials
  - EssentialsChat
  - LuckPerms
  - BlueMap
  - WorldGuard
  - CombatLogX
commands:
  clan:
    description: Handles all clan related commands.
    usage: /clan help
    aliases: [ faction, f ]
  war:
    description: Handles all clan war related commands.
    usage: /war help
    aliases: [ w ]
  chunk:
    description: Handles all chunk related commands.
    usage: /chunk help
    aliases: [ c ]
  confirm:
    description: Confirm your action.
    usage: /confirm
  cancel:
    description: Cancels your action.
    usage: /cancel

